include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    public_member_api_docs: false  # Disable for MVP velocity
    avoid_redundant_argument_values: false
    one_member_abstracts: false  # UseCases have single call() method by design
