import 'package:injectable/injectable.dart';
import 'package:tkd_brackets/features/division/domain/entities/division_entity.dart';
import 'package:tkd_brackets/features/division/domain/entities/division_template.dart';
import 'package:tkd_brackets/features/division/domain/repositories/division_template_repository.dart';
import 'package:tkd_brackets/features/tournament/domain/entities/tournament_entity.dart';

@LazySingleton()
class FederationTemplateRegistry {
  FederationTemplateRegistry(this._repository);

  final DivisionTemplateRepository? _repository;
  final Map<FederationType, List<DivisionTemplate>> _staticTemplates = {};
  bool _initialized = false;

  void _ensureInitialized() {
    if (_initialized) return;
    _loadStaticTemplates();
    _initialized = true;
  }

  void _loadStaticTemplates() {
    _staticTemplates[FederationType.wt] = _createWtTemplates();
    _staticTemplates[FederationType.itf] = _createItfTemplates();
    _staticTemplates[FederationType.ata] = _createAtaTemplates();
  }

  List<DivisionTemplate> getAllTemplates(
    FederationType federation, {
    String? organizationId,
  }) {
    _ensureInitialized();
    final static = List<DivisionTemplate>.from(
      _staticTemplates[federation] ?? [],
    );

    if (organizationId == null || _repository == null) {
      return static;
    }

    // For sync access, we return static templates + cache any previously loaded custom
    // Full integration requires async call to getCustomTemplates
    return static;
  }

  Future<List<DivisionTemplate>> getAllTemplatesWithCustom(
    FederationType federation, {
    String? organizationId,
  }) async {
    _ensureInitialized();
    final static = List<DivisionTemplate>.from(
      _staticTemplates[federation] ?? [],
    );

    if (organizationId == null || _repository == null) {
      return static;
    }

    final customResult = await _repository.getCustomTemplates(organizationId);

    return customResult.fold(
      (failure) => static,
      (customTemplates) => _mergeTemplates(static, customTemplates),
    );
  }

  List<DivisionTemplate> _mergeTemplates(
    List<DivisionTemplate> static,
    List<DivisionTemplate> custom,
  ) {
    final merged = <String, DivisionTemplate>{};

    for (final template in static) {
      merged[template.id] = template;
    }

    for (final template in custom) {
      merged[template.id] = template;
    }

    return merged.values.toList()
      ..sort((a, b) => a.displayOrder.compareTo(b.displayOrder));
  }

  Future<List<DivisionTemplate>> getCustomTemplates(
    String organizationId,
  ) async {
    if (_repository == null) return [];

    final result = await _repository.getCustomTemplates(organizationId);
    return result.fold(
      (failure) => <DivisionTemplate>[],
      (templates) => templates,
    );
  }

  List<DivisionTemplate> getStaticTemplates(FederationType federation) {
    _ensureInitialized();
    return List.from(_staticTemplates[federation] ?? []);
  }

  List<DivisionTemplate> getTemplatesByCategory(
    FederationType federation,
    DivisionCategory category, {
    String? organizationId,
  }) {
    _ensureInitialized();
    return (_staticTemplates[federation] ?? [])
        .where((t) => t.category == category)
        .toList();
  }

  List<DivisionTemplate> getTemplatesByGender(
    FederationType federation,
    DivisionGender gender, {
    String? organizationId,
  }) {
    _ensureInitialized();
    return (_staticTemplates[federation] ?? [])
        .where((t) => t.gender == gender)
        .toList();
  }

  DivisionTemplate? getTemplateById(String templateId) {
    _ensureInitialized();
    for (final templates in _staticTemplates.values) {
      final found = templates.where((t) => t.id == templateId).firstOrNull;
      if (found != null) return found;
    }
    return null;
  }

  Future<DivisionTemplate?> getTemplateByIdWithCustom(
    String templateId, {
    String? organizationId,
  }) async {
    // First check static templates
    final staticResult = getTemplateById(templateId);

    if (organizationId == null || _repository == null) {
      return staticResult;
    }

    // Check custom templates (custom overrides static)
    final customResult = await _repository.getCustomTemplateById(templateId);

    return customResult.fold((failure) => staticResult, (custom) => custom);
  }

  List<DivisionTemplate> _createWtTemplates() {
    final templates = <DivisionTemplate>[];
    var order = 0;

    templates.addAll([
      DivisionTemplate(
        id: 'wt-cadet-male-33',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -33kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 0,
        weightMaxKg: 33,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-37',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -37kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 33,
        weightMaxKg: 37,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-41',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -41kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 37,
        weightMaxKg: 41,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-45',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -45kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 41,
        weightMaxKg: 45,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-49',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -49kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 45,
        weightMaxKg: 49,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-53',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -53kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 49,
        weightMaxKg: 53,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-57',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -57kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 53,
        weightMaxKg: 57,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-61',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -61kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 57,
        weightMaxKg: 61,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-65',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male -65kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 61,
        weightMaxKg: 65,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-male-plus65',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Male +65kg',
        gender: DivisionGender.male,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 65,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-29',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -29kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 0,
        weightMaxKg: 29,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-33',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -33kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 29,
        weightMaxKg: 33,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-37',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -37kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 33,
        weightMaxKg: 37,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-41',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -41kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 37,
        weightMaxKg: 41,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-44',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -44kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 41,
        weightMaxKg: 44,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-47',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -47kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 44,
        weightMaxKg: 47,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-51',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -51kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 47,
        weightMaxKg: 51,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-55',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -55kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 51,
        weightMaxKg: 55,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-59',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female -59kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 55,
        weightMaxKg: 59,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-cadet-female-plus59',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Cadet Female +59kg',
        gender: DivisionGender.female,
        ageMin: 12,
        ageMax: 14,
        weightMinKg: 59,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-46',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male -46kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 0,
        weightMaxKg: 46,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-50',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male -50kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 46,
        weightMaxKg: 50,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-54',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male -54kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 50,
        weightMaxKg: 54,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-58',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male -58kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 54,
        weightMaxKg: 58,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-62',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male -62kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 58,
        weightMaxKg: 62,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-67',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male -67kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 62,
        weightMaxKg: 67,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-72',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male -72kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 67,
        weightMaxKg: 72,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-77',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male -77kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 72,
        weightMaxKg: 77,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-male-plus77',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Male +77kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 77,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-42',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female -42kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 0,
        weightMaxKg: 42,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-44',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female -44kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 42,
        weightMaxKg: 44,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-46',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female -46kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 44,
        weightMaxKg: 46,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-49',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female -49kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 46,
        weightMaxKg: 49,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-52',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female -52kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 49,
        weightMaxKg: 52,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-55',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female -55kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 52,
        weightMaxKg: 55,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-59',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female -59kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 55,
        weightMaxKg: 59,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-63',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female -63kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 59,
        weightMaxKg: 63,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-junior-female-plus63',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Junior Female +63kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 17,
        weightMinKg: 63,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-male-54',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Male -54kg',
        gender: DivisionGender.male,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 0,
        weightMaxKg: 54,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-male-58',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Male -58kg',
        gender: DivisionGender.male,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 54,
        weightMaxKg: 58,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-male-63',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Male -63kg',
        gender: DivisionGender.male,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 58,
        weightMaxKg: 63,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-male-68',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Male -68kg',
        gender: DivisionGender.male,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 63,
        weightMaxKg: 68,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-male-74',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Male -74kg',
        gender: DivisionGender.male,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 68,
        weightMaxKg: 74,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-male-80',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Male -80kg',
        gender: DivisionGender.male,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 74,
        weightMaxKg: 80,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-male-87',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Male -87kg',
        gender: DivisionGender.male,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 80,
        weightMaxKg: 87,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-male-plus87',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Male +87kg',
        gender: DivisionGender.male,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 87,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-female-46',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Female -46kg',
        gender: DivisionGender.female,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 0,
        weightMaxKg: 46,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-female-49',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Female -49kg',
        gender: DivisionGender.female,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 46,
        weightMaxKg: 49,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-female-53',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Female -53kg',
        gender: DivisionGender.female,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 49,
        weightMaxKg: 53,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-female-57',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Female -57kg',
        gender: DivisionGender.female,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 53,
        weightMaxKg: 57,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-female-62',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Female -62kg',
        gender: DivisionGender.female,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 57,
        weightMaxKg: 62,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-female-67',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Female -67kg',
        gender: DivisionGender.female,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 62,
        weightMaxKg: 67,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-female-73',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Female -73kg',
        gender: DivisionGender.female,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 67,
        weightMaxKg: 73,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'wt-senior-female-plus73',
        federation: FederationType.wt,
        category: DivisionCategory.sparring,
        name: 'Senior Female +73kg',
        gender: DivisionGender.female,
        ageMin: 18,
        ageMax: 999,
        weightMinKg: 73,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
    ]);

    return templates;
  }

  List<DivisionTemplate> _createItfTemplates() {
    final templates = <DivisionTemplate>[];
    var order = 0;

    templates.addAll([
      DivisionTemplate(
        id: 'itf-pattern-male-1',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 1 (Chon-Ji)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-male-2',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 2 (Dan-Gun)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-male-3',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 3 (Do-San)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-male-4',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 4 (Won-Hyo)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-male-5',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 5 (Yul-Gok)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-male-6',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 6 (Joong-Gun)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-male-7',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 7 (Toi-Gye)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-male-8',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 8 (Hwa-Rang)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-male-9',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Pattern 9 (Choong-Moo)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-1',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 1 (Chon-Ji)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-2',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 2 (Dan-Gun)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-3',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 3 (Do-San)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-4',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 4 (Won-Hyo)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-5',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 5 (Yul-Gok)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-6',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 6 (Joong-Gun)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-7',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 7 (Toi-Gye)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-8',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 8 (Hwa-Rang)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-female-9',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Pattern 9 (Choong-Moo)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-team-male',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Male Team Pattern',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-team-female',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Female Team Pattern',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-pattern-team-mixed',
        federation: FederationType.itf,
        category: DivisionCategory.poomsae,
        name: 'Mixed Team Pattern',
        gender: DivisionGender.mixed,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-male-54',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Male -54kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 0,
        weightMaxKg: 54,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-male-58',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Male -58kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 54,
        weightMaxKg: 58,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-male-62',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Male -62kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 58,
        weightMaxKg: 62,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-male-67',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Male -67kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 62,
        weightMaxKg: 67,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-male-72',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Male -72kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 67,
        weightMaxKg: 72,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-male-77',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Male -77kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 72,
        weightMaxKg: 77,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-male-82',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Male -82kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 77,
        weightMaxKg: 82,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-male-plus82',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Male +82kg',
        gender: DivisionGender.male,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 82,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-female-46',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Female -46kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 0,
        weightMaxKg: 46,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-female-49',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Female -49kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 46,
        weightMaxKg: 49,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-female-53',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Female -53kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 49,
        weightMaxKg: 53,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-female-57',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Female -57kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 53,
        weightMaxKg: 57,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-female-62',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Female -62kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 57,
        weightMaxKg: 62,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-female-67',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Female -67kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 62,
        weightMaxKg: 67,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-u21-female-plus67',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'U21 Female +67kg',
        gender: DivisionGender.female,
        ageMin: 15,
        ageMax: 20,
        weightMinKg: 67,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-male-57',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Male -57kg',
        gender: DivisionGender.male,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 0,
        weightMaxKg: 57,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-male-67',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Male -67kg',
        gender: DivisionGender.male,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 57,
        weightMaxKg: 67,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-male-77',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Male -77kg',
        gender: DivisionGender.male,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 67,
        weightMaxKg: 77,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-male-87',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Male -87kg',
        gender: DivisionGender.male,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 77,
        weightMaxKg: 87,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-male-plus87',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Male +87kg',
        gender: DivisionGender.male,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 87,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-female-49',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Female -49kg',
        gender: DivisionGender.female,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 0,
        weightMaxKg: 49,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-female-57',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Female -57kg',
        gender: DivisionGender.female,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 49,
        weightMaxKg: 57,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-female-67',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Female -67kg',
        gender: DivisionGender.female,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 57,
        weightMaxKg: 67,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-female-77',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Female -77kg',
        gender: DivisionGender.female,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 67,
        weightMaxKg: 77,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'itf-sparring-senior-female-plus77',
        federation: FederationType.itf,
        category: DivisionCategory.sparring,
        name: 'Senior Female +77kg',
        gender: DivisionGender.female,
        ageMin: 21,
        ageMax: 999,
        weightMinKg: 77,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
    ]);

    return templates;
  }

  List<DivisionTemplate> _createAtaTemplates() {
    final templates = <DivisionTemplate>[];
    var order = 0;

    templates.addAll([
      DivisionTemplate(
        id: 'ata-forms-songahm-1',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 1 (White)',
        gender: DivisionGender.male,
        beltRankMin: 'white',
        beltRankMax: 'white',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-2',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 2 (Yellow)',
        gender: DivisionGender.male,
        beltRankMin: 'yellow',
        beltRankMax: 'yellow',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-3',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 3 (Orange)',
        gender: DivisionGender.male,
        beltRankMin: 'orange',
        beltRankMax: 'orange',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-4',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 4 (Green)',
        gender: DivisionGender.male,
        beltRankMin: 'green',
        beltRankMax: 'green',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-5',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 5 (Blue)',
        gender: DivisionGender.male,
        beltRankMin: 'blue',
        beltRankMax: 'blue',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-6',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 6 (Brown)',
        gender: DivisionGender.male,
        beltRankMin: 'brown',
        beltRankMax: 'brown',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-7',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 7 (Red)',
        gender: DivisionGender.male,
        beltRankMin: 'red',
        beltRankMax: 'red',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-8',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 8 (Red/Black 1)',
        gender: DivisionGender.male,
        beltRankMin: 'red',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-9',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 9 (Red/Black 2)',
        gender: DivisionGender.male,
        beltRankMin: 'red',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-10',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 10 (Red/Black 3)',
        gender: DivisionGender.male,
        beltRankMin: 'red',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-11',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 11 (Black 1)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-12',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 12 (Black 2)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-13',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 13 (Black 3)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-14',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 14 (Black 4)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-15',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 15 (Black 5)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-16',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 16 (Black 6)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-17',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 17 (Black 7)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-18',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 18 (Black 8)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-19',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 19 (Black 9)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-20',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 20 (Black 10)',
        gender: DivisionGender.male,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-1',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 1 (White)',
        gender: DivisionGender.female,
        beltRankMin: 'white',
        beltRankMax: 'white',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-2',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 2 (Yellow)',
        gender: DivisionGender.female,
        beltRankMin: 'yellow',
        beltRankMax: 'yellow',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-3',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 3 (Orange)',
        gender: DivisionGender.female,
        beltRankMin: 'orange',
        beltRankMax: 'orange',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-4',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 4 (Green)',
        gender: DivisionGender.female,
        beltRankMin: 'green',
        beltRankMax: 'green',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-5',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 5 (Blue)',
        gender: DivisionGender.female,
        beltRankMin: 'blue',
        beltRankMax: 'blue',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-6',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 6 (Brown)',
        gender: DivisionGender.female,
        beltRankMin: 'brown',
        beltRankMax: 'brown',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-7',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 7 (Red)',
        gender: DivisionGender.female,
        beltRankMin: 'red',
        beltRankMax: 'red',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-8',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 8 (Red/Black 1)',
        gender: DivisionGender.female,
        beltRankMin: 'red',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-9',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 9 (Red/Black 2)',
        gender: DivisionGender.female,
        beltRankMin: 'red',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-10',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 10 (Red/Black 3)',
        gender: DivisionGender.female,
        beltRankMin: 'red',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-11',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 11 (Black 1)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-12',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 12 (Black 2)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-13',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 13 (Black 3)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-14',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 14 (Black 4)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-15',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 15 (Black 5)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-16',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 16 (Black 6)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-17',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 17 (Black 7)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-18',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 18 (Black 8)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-19',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 19 (Black 9)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-forms-songahm-female-20',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Songahm 20 (Black 10)',
        gender: DivisionGender.female,
        beltRankMin: 'black',
        beltRankMax: 'black',
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-weapons-male',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Weapons Forms (Male)',
        gender: DivisionGender.male,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-weapons-female',
        federation: FederationType.ata,
        category: DivisionCategory.poomsae,
        name: 'Weapons Forms (Female)',
        gender: DivisionGender.female,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-combat-male-lightweight',
        federation: FederationType.ata,
        category: DivisionCategory.sparring,
        name: 'Combat Sparring Male Lightweight',
        gender: DivisionGender.male,
        weightMinKg: 0,
        weightMaxKg: 55,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-combat-male-middleweight',
        federation: FederationType.ata,
        category: DivisionCategory.sparring,
        name: 'Combat Sparring Male Middleweight',
        gender: DivisionGender.male,
        weightMinKg: 55,
        weightMaxKg: 75,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-combat-male-heavyweight',
        federation: FederationType.ata,
        category: DivisionCategory.sparring,
        name: 'Combat Sparring Male Heavyweight',
        gender: DivisionGender.male,
        weightMinKg: 75,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-combat-female-lightweight',
        federation: FederationType.ata,
        category: DivisionCategory.sparring,
        name: 'Combat Sparring Female Lightweight',
        gender: DivisionGender.female,
        weightMinKg: 0,
        weightMaxKg: 50,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-combat-female-middleweight',
        federation: FederationType.ata,
        category: DivisionCategory.sparring,
        name: 'Combat Sparring Female Middleweight',
        gender: DivisionGender.female,
        weightMinKg: 50,
        weightMaxKg: 65,
        displayOrder: order++,
      ),
      DivisionTemplate(
        id: 'ata-combat-female-heavyweight',
        federation: FederationType.ata,
        category: DivisionCategory.sparring,
        name: 'Combat Sparring Female Heavyweight',
        gender: DivisionGender.female,
        weightMinKg: 65,
        weightMaxKg: 999,
        displayOrder: order++,
      ),
    ]);

    return templates;
  }
}
